/*** File generated by GenISSLib version 3.0.2: DO NOT MODIFY ***/
#ifndef ____unisim_component_cxx_processor_mips_isa_mipsel_unisim__component__cxx__processor__mips__isa_HH__
#define ____unisim_component_cxx_processor_mips_isa_mipsel_unisim__component__cxx__processor__mips__isa_HH__
#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
#endif

#include <vector>
#include <inttypes.h>
#include <cstring>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace mips { namespace isa {
typedef uint32_t CodeType;

template <
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
typename
#line 18 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
ARCH
#line 21 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
>
class Operation;
const unsigned int NUM_OPERATIONS_PER_PAGE = 4096;
template <
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
typename
#line 28 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
ARCH
#line 31 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
>
class DecodeMapPage
{
public:
	DecodeMapPage(uint32_t key);
	~DecodeMapPage();
	uint32_t key;
	DecodeMapPage *next;
	Operation<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 43 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> *operation[NUM_OPERATIONS_PER_PAGE];
};

template <
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
typename
#line 50 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
ARCH
#line 53 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
>
class DecodeTableEntry
{
public:
	DecodeTableEntry(CodeType opcode, CodeType opcode_mask, Operation<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 61 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> *(*decode)(CodeType, uint32_t));
	CodeType opcode;
	CodeType opcode_mask;
	Operation<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 68 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> *(*decode)(CodeType code, uint32_t addr);
};
const unsigned int NUM_DECODE_HASH_TABLE_ENTRIES = 4096;
template <
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
typename
#line 75 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
ARCH
#line 78 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
>
class Decoder
{
public:
	Decoder();
	virtual ~Decoder();

	Operation<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 89 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	>*NCDecode(uint32_t addr);
	Operation<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 94 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> *NCDecode(uint32_t addr, CodeType code);
	Operation<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 99 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> *Decode(uint32_t addr, CodeType insn);
	std::vector<DecodeTableEntry<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 104 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> > const& GetDecodeTable() const { return decode_table; };
	void InvalidateDecodingCacheEntry(uint32_t addr);
	void InvalidateDecodingCache();

	void SetLittleEndian();
	void SetBigEndian();
private:
	std::vector<DecodeTableEntry<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 115 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> > decode_table;
	DecodeMapPage<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 120 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> *mru_page;
	DecodeMapPage<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 125 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> *decode_hash_table[NUM_DECODE_HASH_TABLE_ENTRIES];
	DecodeMapPage<
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH
#line 130 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	> *FindPage(uint32_t page_key)
#if defined(__GNUC__) && (__GNUC__ >= 3 && (__GNUC__ != 3 || __GNUC_MINOR__ != 4 || __GNUC_PATCHLEVEL__ != 6))
	__attribute__((always_inline))
#endif
	;
};

} } } } } }
#line 47 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"

#include <iosfwd>
#include <cstdint>
#line 143 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
namespace unisim { namespace component { namespace cxx { namespace processor { namespace mips { namespace isa {
template <
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
typename
#line 148 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
#line 45 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
ARCH
#line 151 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
>
class Operation
{
public:
	Operation(CodeType code, uint32_t addr, const char *name);
	virtual ~Operation();
	inline uint32_t GetAddr() const { return addr; }
	inline void SetAddr(uint32_t _addr) { this->addr = _addr; }
	inline CodeType GetEncoding() const { return encoding; }
	inline unsigned int GetLength() const { return 32; }
	inline const char *GetName() const { return name; }
	static unsigned int const minsize = 32;
	static unsigned int const maxsize = 32;
	virtual
#line 56 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	void
#line 168 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	execute(
#line 56 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	ARCH&
#line 172 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
#line 56 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	core
#line 175 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	) const;
	virtual
#line 52 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	void
#line 180 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	disasm(
#line 52 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	std::ostream&
#line 184 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
#line 52 "./unisim/component/cxx/processor/mips/isa/mipsel.isa"
	sink
#line 187 "./unisim/component/cxx/processor/mips/isa/mipsel.hh"
	) const;
protected:
	CodeType encoding;
	uint32_t addr;
	const char *name;
};

} } } } } }
#endif
